In [1]:
import pandas as pd # library for dataframe
import numpy as np
#import matplotlib.pyplot as plt

In [2]:

#read data into the notebook using pd.read_csv

df = pd.read_csv("Hydra-Movie-Scrape.csv")

In [3]:
df.head()

Title  Year  \
0                        Patton Oswalt: Annihilation  2017   
1                                      New York Doll  2005   
2  Mickey's Magical Christmas: Snowed in at the H...  2001   
3                         Mickey's House of Villains  2001   
4                                      And Then I Go  2017   

                                             Summary  \
0  Patton Oswald, despite a personal tragedy, pro...   
1  A recovering alcoholic and recently converted ...   
2  After everyone is snowed in at the House of Mo...   
3  The villains from the popular animated Disney ...   
4  In the cruel world of junior high, Edwin suffe...   

                                       Short Summary  \
0  Patton Oswalt, despite a personal tragedy, pro...   
1  A recovering alcoholic and recently converted ...   
2  Mickey and all his friends hold their own Chri...   
3  The villains from the popular animated Disney ...   
4  In the cruel world of junior high, Edwin suffe...   

                                      Genres    IMDB ID  Runtime  \
0                              Uncategorized  tt7026230       66   
1                          Documentary|Music  tt0436629       75   
2  Adventure|Animation|Comedy|Family|Fantasy  tt0300195       65   
3     Animation|Comedy|Family|Fantasy|Horror  tt0329374        0   
4                                      Drama  tt2018111       99   

  YouTube Trailer  Rating                                       Movie Poster  \
0     4hZi5QaMBFc     7.4  https://hydramovies.com/wp-content/uploads/201...   
1     jwD04NsnLLg     7.9  https://hydramovies.com/wp-content/uploads/201...   
2     uCKwHHftrU4     6.8  https://hydramovies.com/wp-content/uploads/201...   
3     JA03ciYt-Ek     6.6  https://hydramovies.com/wp-content/uploads/201...   
4     8CdIiD6-iF0     7.6  https://hydramovies.com/wp-content/uploads/201...   

            Director        Writers                            Cast  
0  Bobcat Goldthwait  Patton Oswalt                   Patton Oswalt  
1      Greg Whiteley    Arthur Kane                 Sylvain Sylvain  
2         Tony Craig    Thomas Hart  Carlos Alazraqui|Wayne Allwine  
3     Jamie Mitchell    Thomas Hart      Tony Anselmo|Wayne Allwine  
4    Vincent Grashaw    Brett Haley        Arman Darbo|Sawyer Barth

In [4]:
print(df.columns)
print(df.shape)

Index(['Title', 'Year', 'Summary', 'Short Summary', 'Genres', 'IMDB ID',
       'Runtime', 'YouTube Trailer', 'Rating', 'Movie Poster', 'Director',
       'Writers', 'Cast'],
      dtype='object')
(3940, 13)


In [5]:
df.Summary.fillna('None',inplace=True)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3940 entries, 0 to 3939
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Title            3940 non-null   object 
 1   Year             3940 non-null   int64  
 2   Summary          3940 non-null   object 
 3   Short Summary    3939 non-null   object 
 4   Genres           3940 non-null   object 
 5   IMDB ID          3940 non-null   object 
 6   Runtime          3940 non-null   int64  
 7   YouTube Trailer  3893 non-null   object 
 8   Rating           3940 non-null   float64
 9   Movie Poster     3940 non-null   object 
 10  Director         3940 non-null   object 
 11  Writers          3922 non-null   object 
 12  Cast             3916 non-null   object 
dtypes: float64(1), int64(2), object(10)
memory usage: 246.3+ KB
None


In [6]:
Gen = df.Genres
print(type(Gen[1]))
print(Gen[1].split('|'))
Gen_splited =[]

for i in Gen:
    x = i.split('|')
    Gen_splited.append(x)

<class 'str'>
['Documentary', 'Music']


In [7]:
Gen_splited[:10]

[['Uncategorized'],
 ['Documentary', 'Music'],
 ['Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Animation', 'Comedy', 'Family', 'Fantasy', 'Horror'],
 ['Drama'],
 ['Animation', 'Comedy', 'Family', 'Sport'],
 ['Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Uncategorized'],
 ['Uncategorized'],
 ['Drama']]

In [8]:
x=[]
for i in Gen_splited:
    x= x+i
x = set(x)

In [9]:
Anima = []
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Animation":
            x=1
    Anima.append(x)
    #print(f"{j} : {x}")
##########3
Action = []
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Action":
            x=1
    Action.append(x)
Adv=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Adventure":
            x=1
    Adv.append(x)
Bio=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Biography":
            x=1
    Bio.append(x)
Com=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Comedy":
            x=1
    Com.append(x)
Cri=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Crime":
            x=1
    Cri.append(x)
Doc=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Documentary":
            x=1
    Doc.append(x)
Dra=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Drama":
            x=1
    Dra.append(x)
Fam=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Family":
            x=1
    Fam.append(x)
Fan=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Fantasy":
            x=1
    Fan.append(x)
His=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "History":
            x=1
    His.append(x)
Hor=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Horror":
            x=1
    Hor.append(x)
Ms=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Music":
            x=1
    Ms.append(x)
Msc=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Musical":
            x=1
    Msc.append(x)
Mys=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Mystery":
            x=1
    Mys.append(x)
New=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "News":
            x=1
    New.append(x)
Rea=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Reality-TV":
            x=1
    Rea.append(x)
Rom=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Romance":
            x=1
    Rom.append(x)
Sci=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Sci-Fi":
            x=1
    Sci.append(x)
Spo=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Sport":
            x=1
    Spo.append(x)
Thr=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Thriller":
            x=1
    Thr.append(x)
Unc=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Uncategorized":
            x=1
    Unc.append(x)
War=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "War":
            x=1
    War.append(x)
Wes=[]
for i in Gen_splited:
    for j in i:
        x=0
        if j == "Western":
            x=1
    Wes.append(x)


In [10]:
df2 = pd.DataFrame(Action,columns=['Action'])
df2.reset_index
df3 = pd.DataFrame(Adv,columns=['Advanture'])
df4 = pd.DataFrame(Anima,columns=['Animation'])
df5 = pd.DataFrame(Bio,columns=['Biography'])
df6 = pd.DataFrame(Com,columns=['Comedy'])
df7 = pd.DataFrame(Cri,columns=['Crime'])
df8 = pd.DataFrame(Dra,columns=['Drama'])
df9 = pd.DataFrame(Doc,columns=['Documentary'])
df10 = pd.DataFrame(Fam,columns=['Family'])
df11 = pd.DataFrame(Fan,columns=['Fantasy'])
df12 = pd.DataFrame(His,columns=['History'])
df13 = pd.DataFrame(Hor,columns=['Horror'])
df14 = pd.DataFrame(Ms,columns=['Music'])
df15 = pd.DataFrame(Msc,columns=['Musical'])
df16 = pd.DataFrame(Mys,columns=['Mystery'])
df17 = pd.DataFrame(New,columns=['News'])
df18 = pd.DataFrame(Rea,columns=['Reality-Show'])
df19 = pd.DataFrame(Rom,columns=['Romance'])
df20 = pd.DataFrame(Sci,columns=['Sci-fi'])
df21 = pd.DataFrame(Spo,columns=['Sport'])
df22 = pd.DataFrame(Thr,columns=['Thriller'])
df23 = pd.DataFrame(Unc,columns=['Uncategorized'])
df24 = pd.DataFrame(War,columns=['War'])
df25 = pd.DataFrame(Wes,columns=['Western'])



In [11]:
df2['Adventure'] = df3
df2['Animation'] = df4
df2['Biography'] = df5
df2['Comedy'] = df6
df2['Crime'] = df7
df2['Drama'] = df8
df2['Documentary'] = df9
df2['Family'] = df10
df2['Fantasy'] = df11
df2['History'] = df12
df2['Horror'] = df13
df2['Music'] = df14
df2['Musical'] = df15
df2['Mystery'] = df16
df2['News'] = df17
df2['Reality-Show'] = df18
df2['Romance'] = df19
df2['Sci-fi'] = df20
df2['Sport'] = df21
df2['Thriller'] = df22
df2['Uncategorized'] = df23
df2['War'] = df24
df2['Western'] = df25


In [12]:
df2.head()

Action  Adventure  Animation  Biography  Comedy  Crime  Drama  Documentary  \
0       0          0          0          0       0      0      0            0   
1       0          0          0          0       0      0      0            0   
2       0          0          0          0       0      0      0            0   
3       0          0          0          0       0      0      0            0   
4       0          0          0          0       0      0      1            0   

   Family  Fantasy  ...  Mystery  News  Reality-Show  Romance  Sci-fi  Sport  \
0       0        0  ...        0     0             0        0       0      0   
1       0        0  ...        0     0             0        0       0      0   
2       0        1  ...        0     0             0        0       0      0   
3       0        0  ...        0     0             0        0       0      0   
4       0        0  ...        0     0             0        0       0      0   

   Thriller  Uncategorized  War  Western  
0         0              1    0        0  
1         0              0    0        0  
2         0              0    0        0  
3         0              0    0        0  
4         0              0    0        0  

[5 rows x 24 columns]

In [13]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
#nltk.download('punkt')

In [14]:
Sum = df.Summary

In [15]:
Sum[1]

'A recovering alcoholic and recently converted Mormon, Arthur "Killer" Kane, of the rock band The New York Dolls, is given a chance at reuniting with his band after 30 years.'

In [16]:
tokens = word_tokenize(Sum[1])

In [17]:
print(tokens)

['A', 'recovering', 'alcoholic', 'and', 'recently', 'converted', 'Mormon', ',', 'Arthur', '``', 'Killer', "''", 'Kane', ',', 'of', 'the', 'rock', 'band', 'The', 'New', 'York', 'Dolls', ',', 'is', 'given', 'a', 'chance', 'at', 'reuniting', 'with', 'his', 'band', 'after', '30', 'years', '.']


In [18]:
import string
stop = stopwords.words('english')#+ list(string.punctuation)
#nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
lemma = WordNetLemmatizer()

In [19]:
def rev_stop(text):
    new_text=[]
    for i in text: 
        if i.lower() not in stop:
            i = porter.stem(i)
            i = lemma.lemmatize(i)
            
            new_text.append(i)
    return new_text

In [20]:
#rev_stop(tokens)
import nltk
#nltk.download('wordnet')
Sum_tokenized=[]
for i in Sum:
    x = rev_stop(word_tokenize(i))
    Sum_tokenized.append(x)

In [21]:
#Sum_tokenized

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
vectorizer = TfidfVectorizer()
Sum_all_tokenized = [" ". join(x) for x in Sum_tokenized]
X = vectorizer.fit_transform(Sum_all_tokenized)
#print(vectorizer.get_feature_names())

In [24]:
#print(X.shape)
#print(vectorizer.get_feature_names())

In [25]:
#dense = X.todense()

In [53]:
from sklearn.metrics.pairwise import euclidean_distances

def recommend(text):
    text = str(text)
    Sum =df.Summary
    Sum.loc[3940]= text 
    Title = df.Title
    Title.loc[3940] = text 
    
    textz = pd.Series([text],index =['3940'])
    Sum.append(textz)
    Sum_tokenized=[]
    for i in Sum:
        x = rev_stop(word_tokenize(i))
        Sum_tokenized.append(x)
    basket=[]
    vectorizer = TfidfVectorizer()
    Sum_all_tokenized = [" ". join(x) for x in Sum_tokenized]
    X = vectorizer.fit_transform(Sum_all_tokenized)
    dense = X.toarray()
    for i in dense[:-1]:
        basket.append(euclidean_distances([dense[-1]],[i]))
    z= min(basket)
    return z,Title[basket.index(z)],Sum[basket.index(z)]

In [58]:
# I don't exactly know the problem but without[] the function will just ask for 2D array so this is the way to solve it


# this will give you the recommended movie based on what you type

print(recommend(" Samurai "))
print(recommend(" Car racing"))

(array([[1.17577967]]), 'Hana', "In 1702, set against the backdrop of a long-delayed and insatiable revenge, a reserved samurai, Aoki Sozaemon, leaves his hometown in Matsumoto to come to bustling Edo in search of his father's killer. Unaccomplished as a swordsman, with his funds quickly drying up, Sozaemon must honour his clan's demand to avenge a disgraceful death, however, when he finally finds his target, he will have to make a difficult decision before a crushing dilemma. Is the way of the samurai stronger than the way of the heart?")
(array([[1.13984816]]), 'The Fast and the Furious: Tokyo Drift', 'An American teenager named Sean Boswell is a loner in school, however he challenges his rival for an illegal street racing, and he totals his car in the end of the race. To avoid time in prison he is sent to Tokyo to live with his father who is in the military. As soon as he arrives he discovers a new, fun but dangerous way of street racing in the underworld of the streets of Tokyo, Ja

In [63]:
# this will give you the recommended movie based on what you type

print(recommend("Car racing"))

(array([[1.13984816]]), 'The Fast and the Furious: Tokyo Drift', 'An American teenager named Sean Boswell is a loner in school, however he challenges his rival for an illegal street racing, and he totals his car in the end of the race. To avoid time in prison he is sent to Tokyo to live with his father who is in the military. As soon as he arrives he discovers a new, fun but dangerous way of street racing in the underworld of the streets of Tokyo, Japan.')
